import { writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import type { Workspace } from './Workspace.ts';
import type { PmBinary } from './PmBinary.ts';
import type { Logger } from './Logger.ts';

/**
 * Writes /brain/DATA-STATE.md — what is configured versus what has actually been synced.
 *
 * Without it the agent can only see the tables that exist, so a stream that is configured
 * but never synced is indistinguishable from one that does not exist. That produced the
 * dead-end answer "there are no PR records" when a github connection was sitting right
 * there able to pull them. With this file the agent can say what is missing, whether it is
 * extractable, and request it.
 */
export class DataState {
  constructor(
    private readonly workspace: Workspace,
    private readonly pm: PmBinary,
    private readonly log: Logger,
  ) {}

  /** Streams a connector can expose, from pm's compiled manifest. */
  private availableStreams(connector: string): string[] {
    const out = this.pm.execTolerant<{ manifest?: { streams?: Array<{ name?: string }> } }>(
      ['connectors', 'inspect', connector],
    );
    const streams = out.envelope?.manifest?.streams ?? [];
    return streams.map((s) => String(s.name ?? '')).filter(Boolean);
  }

  private rowCount(parquetPath: string): string {
    const duckdb = spawnSync('duckdb', ['-noheader', '-list', '-c',
      `SELECT count(*) FROM read_parquet('${parquetPath.replace(/'/g, "''")}');`], { encoding: 'utf8' });
    const value = (duckdb.stdout ?? '').trim().split('\n').pop()?.trim();
    return duckdb.status === 0 && value ? value : '?';
  }

  write(syncedTables: string[]): void {
    const config = this.workspace.loadConfig() as unknown as Record<string, unknown>;
    const connectors = (config.connectors ?? []) as Array<{
      connector: string; credential?: string;
      config?: Record<string, unknown>;
      streams?: Array<{ name: string; table?: string }>;
    }>;

    const lines: string[] = [
      '# Data state',
      '',
      '_Generated by `brain sync` / `brain setup`. Lists what is configured against what has',
      'actually been extracted. If a stream is configured but not synced, the data can be',
      'pulled — see "When the data you need is not there" in AGENT-BRIEF.md._',
      '',
    ];

    if (connectors.length === 0) {
      lines.push('No connections are configured. Nothing can be extracted until one is added.', '');
    }

    for (const entry of connectors) {
      const available = this.availableStreams(entry.connector);
      const configured = entry.streams ?? [];
      lines.push(`## ${entry.connector}`, '');
      const scope = Object.entries(entry.config ?? {})
        .filter(([k]) => !/token|key|secret|password/i.test(k))
        .map(([k, v]) => `${k}=${String(v)}`)
        .join(' · ');
      if (scope) lines.push(`Scope: ${scope}`, '');

      lines.push('| stream | table | synced |', '|---|---|---|');
      for (const stream of configured) {
        const table = stream.table ?? stream.name;
        const match = syncedTables.find((t) => t.endsWith(`/${table}.parquet`));
        const rows = match ? this.rowCount(join(this.workspace.warehouseDir, match)) : '';
        lines.push(`| ${stream.name} | ${table} | ${match ? `yes — ${rows} rows` : '**no — not extracted yet**'} |`);
      }
      lines.push('');

      const notConfigured = available.filter((s) => !configured.some((c) => c.name === s));
      if (notConfigured.length > 0) {
        lines.push(
          `Also available from this connector, not extracted yet (${notConfigured.length}): ` +
          `${notConfigured.slice(0, 40).join(', ')}${notConfigured.length > 40 ? ', …' : ''}`,
          '',
          'These use credentials that are already configured, so they can be requested the ' +
          'same way — see "Requesting extraction" below. Adding a *new connector* is different: ' +
          'that needs credentials and is a host change.',
          '',
        );
      }
    }

    lines.push(
      '## Requesting extraction',
      '',
      'Write `/workspace/requests/sync.json`:',
      '',
      '```json',
      '{"connection": "<connection name>", "streams": ["<stream>"], "reason": "<why>"}',
      '```',
      '',
      'The host runs it when your turn ends and reports back in the same thread.',
      '',
    );

    const path = join(this.workspace.brainDir, 'DATA-STATE.md');
    writeFileSync(path, lines.join('\n'));
    this.log.ok(`data state written — ${connectors.length} connection(s)`);
  }
}
